name: AuthoringAssistantMocked

on:
  workflow_dispatch:
  push:
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          node-version: 22
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '22'
      - name: Install dependencies
        run: |
          yarn install-dependencies
      - name: Deploy LLM Tool
        run: |
          yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.LLM_PROMPT_EXECUTOR_TOKEN }}
      - name: Launch Prompt Tests
        run: |
          yarn install
          yarn test-mock
          yarn generate-charts
          yarn puppeteer browsers install chrome
          yarn puppeteer browsers install firefox
          yarn test-websites
