name: DeployWebsite
on:
  push:
    paths-ignore:
      - 'obsolete/**'
      - 'sec/**'
      - 'tex/**'
  pull_request:
    paths-ignore:
      - 'obsolete/**'
      - 'sec/**'
      - 'tex/**'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: |
        shopt -s extglob nullglob globstar
      if: runner.os == 'Linux'
    - name: run-test
      run: |
        yarn install
        set -x -e
        export PUPPETEER_CACHE_DIR=$GITHUB_WORKSPACE/
        # requires Puppeteer to be installed at same version as used in Fluid
        yarn puppeteer browsers install chrome
        yarn puppeteer browsers install firefox
        yarn bundle-website authoring-assistant
        yarn website-test authoring-assistant

  deploy-website:
    runs-on: ubuntu-22.04
    needs: test
    # Use branch 'website' to experiment with deploy-website
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/website'
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          yarn install
          set -x -e
          yarn bundle-website authoring-assistant
      - name: gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/authoring-assistant
          keep_files: false
