name: test-misc-website

on:
  workflow_dispatch: 

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: enable-glob
      run: | 
        shopt -s extglob nullglob globstar
    - name: run-test
      run: |
        cd promptExecutor
        yarn install
        set -x -e
        yarn add puppeteer
        npx @puppeteer/browsers install chrome@128.0.6613.84
        npx @puppeteer/browsers install firefox
        yarn fluid publish -w Misc -l
        yarn website-test misc
